-- Every function below is SECURITY DEFINER and re-checks is_admin() itself (belt and
-- braces on top of `grant execute ... to authenticated`), and writes its mutation plus
-- the matching audit_log row atomically in one transaction.
--
-- These are meant to be called through the admin's own authenticated Supabase session
-- (not a shared service-role connection): auth.uid() is how "who did this" gets
-- attributed, and that only resolves correctly when the caller has a real user JWT.
-- Carried forward to Phase 4/5/6 as a constraint on how their Server Actions connect.

-- Transition an order's status (neu / rechnung_versendet / bezahlt / storniert).
create or replace function public.transition_order_status(p_order_id uuid, p_new_status text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old_status text;
begin
  if not public.is_admin() then
    raise exception 'only admins can transition order status';
  end if;

  if p_new_status not in ('neu', 'rechnung_versendet', 'bezahlt', 'storniert') then
    raise exception 'invalid order status %', p_new_status;
  end if;

  select status into v_old_status from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'order % not found', p_order_id;
  end if;

  update public.orders set status = p_new_status where id = p_order_id;

  insert into public.audit_log (entity_type, entity_id, action, field_name, old_value, new_value, actor_type, actor_admin_id)
  values ('order', p_order_id, 'status_change', 'status', v_old_status, p_new_status, 'admin', auth.uid());
end;
$$;

grant execute on function public.transition_order_status(uuid, text) to authenticated;

-- Toggle whether a cancelled/paid order still owes a manual refund (D16). This can
-- never be automated - there is no payment provider to detect the refund - so this
-- is a purely manually-maintained marker end to end.
create or replace function public.set_refund_owed(p_order_id uuid, p_owed boolean)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old boolean;
begin
  if not public.is_admin() then
    raise exception 'only admins can change refund_owed';
  end if;

  select refund_owed into v_old from public.orders where id = p_order_id for update;
  if not found then
    raise exception 'order % not found', p_order_id;
  end if;

  update public.orders set refund_owed = p_owed where id = p_order_id;

  insert into public.audit_log (entity_type, entity_id, action, field_name, old_value, new_value, actor_type, actor_admin_id)
  values ('order', p_order_id, 'refund_owed_change', 'refund_owed', v_old::text, p_owed::text, 'admin', auth.uid());
end;
$$;

grant execute on function public.set_refund_owed(uuid, boolean) to authenticated;

-- Rename the holder of an already-issued ticket (D18: allowed for any ticket, not
-- just Red Castle Club batches - reverses an earlier "non-transferable means fixed
-- forever" assumption).
create or replace function public.rename_ticket_holder(p_ticket_id uuid, p_new_holder_name text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old_name text;
begin
  if not public.is_admin() then
    raise exception 'only admins can rename ticket holders';
  end if;

  select holder_name into v_old_name from public.tickets where id = p_ticket_id for update;
  if not found then
    raise exception 'ticket % not found', p_ticket_id;
  end if;

  update public.tickets set holder_name = p_new_holder_name where id = p_ticket_id;

  insert into public.audit_log (entity_type, entity_id, action, field_name, old_value, new_value, actor_type, actor_admin_id)
  values ('ticket', p_ticket_id, 'holder_name_change', 'holder_name', v_old_name, p_new_holder_name, 'admin', auth.uid());
end;
$$;

grant execute on function public.rename_ticket_holder(uuid, text) to authenticated;

-- Reissue a lost ticket (D6): void the old one (status ersetzt, never deleted) and
-- issue a fresh token as its replacement, linked via replaces_ticket_id. The new
-- token's value is generated by the caller (Phase 6 owns the HMAC token scheme) and
-- passed in here.
create or replace function public.reissue_ticket(
  p_old_ticket_id uuid,
  p_new_token text,
  p_new_holder_name text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old public.tickets%rowtype;
  v_new_id uuid;
begin
  if not public.is_admin() then
    raise exception 'only admins can reissue tickets';
  end if;

  select * into v_old from public.tickets where id = p_old_ticket_id for update;
  if not found then
    raise exception 'ticket % not found', p_old_ticket_id;
  end if;

  if v_old.status = 'ersetzt' then
    raise exception 'ticket % has already been replaced', p_old_ticket_id;
  end if;

  insert into public.tickets (token, order_item_id, product_id, season, holder_name, transferable, replaces_ticket_id)
  values (
    p_new_token,
    v_old.order_item_id,
    v_old.product_id,
    v_old.season,
    coalesce(p_new_holder_name, v_old.holder_name),
    v_old.transferable,
    v_old.id
  )
  returning id into v_new_id;

  update public.tickets set status = 'ersetzt' where id = p_old_ticket_id;

  insert into public.audit_log (entity_type, entity_id, action, field_name, old_value, new_value, actor_type, actor_admin_id, note)
  values ('ticket', p_old_ticket_id, 'reissue', 'status', v_old.status, 'ersetzt', 'admin', auth.uid(), 'replaced by ticket ' || v_new_id::text);

  insert into public.audit_log (entity_type, entity_id, action, actor_type, actor_admin_id, note)
  values ('ticket', v_new_id, 'reissue', 'admin', auth.uid(), 'replaces ticket ' || p_old_ticket_id::text);

  return v_new_id;
end;
$$;

grant execute on function public.reissue_ticket(uuid, text, text) to authenticated;

-- Edit non-price product attributes. Price changes are logged separately and
-- automatically by the price_history trigger - this covers everything else.
create or replace function public.update_product_details(
  p_product_id uuid,
  p_name text default null,
  p_description text default null,
  p_benefits jsonb default null,
  p_tier_level smallint default null,
  p_sort_order integer default null,
  p_active boolean default null
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_old public.products%rowtype;
begin
  if not public.is_admin() then
    raise exception 'only admins can edit products';
  end if;

  select * into v_old from public.products where id = p_product_id for update;
  if not found then
    raise exception 'product % not found', p_product_id;
  end if;

  update public.products set
    name = coalesce(p_name, name),
    description = coalesce(p_description, description),
    benefits = coalesce(p_benefits, benefits),
    tier_level = coalesce(p_tier_level, tier_level),
    sort_order = coalesce(p_sort_order, sort_order),
    active = coalesce(p_active, active)
  where id = p_product_id;

  if p_name is not null and p_name is distinct from v_old.name then
    insert into public.audit_log (entity_type, entity_id, action, field_name, old_value, new_value, actor_type, actor_admin_id)
    values ('product', p_product_id, 'details_change', 'name', v_old.name, p_name, 'admin', auth.uid());
  end if;
  if p_description is not null and p_description is distinct from v_old.description then
    insert into public.audit_log (entity_type, entity_id, action, field_name, old_value, new_value, actor_type, actor_admin_id)
    values ('product', p_product_id, 'details_change', 'description', v_old.description, p_description, 'admin', auth.uid());
  end if;
  if p_benefits is not null and p_benefits is distinct from v_old.benefits then
    insert into public.audit_log (entity_type, entity_id, action, field_name, old_value, new_value, actor_type, actor_admin_id)
    values ('product', p_product_id, 'details_change', 'benefits', v_old.benefits::text, p_benefits::text, 'admin', auth.uid());
  end if;
  if p_tier_level is not null and p_tier_level is distinct from v_old.tier_level then
    insert into public.audit_log (entity_type, entity_id, action, field_name, old_value, new_value, actor_type, actor_admin_id)
    values ('product', p_product_id, 'details_change', 'tier_level', v_old.tier_level::text, p_tier_level::text, 'admin', auth.uid());
  end if;
  if p_sort_order is not null and p_sort_order is distinct from v_old.sort_order then
    insert into public.audit_log (entity_type, entity_id, action, field_name, old_value, new_value, actor_type, actor_admin_id)
    values ('product', p_product_id, 'details_change', 'sort_order', v_old.sort_order::text, p_sort_order::text, 'admin', auth.uid());
  end if;
  if p_active is not null and p_active is distinct from v_old.active then
    insert into public.audit_log (entity_type, entity_id, action, field_name, old_value, new_value, actor_type, actor_admin_id)
    values ('product', p_product_id, 'details_change', 'active', v_old.active::text, p_active::text, 'admin', auth.uid());
  end if;
end;
$$;

grant execute on function public.update_product_details(uuid, text, text, jsonb, smallint, integer, boolean) to authenticated;
